name: Payment Function

on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}
            - name: Deploy Get All Payment Function
              run: aws lambda update-function-code --function-name getAllPaymentDetails --zip-file fileb://backend/confirm_booking_payment/get-all-payment-package.zip
            - name: Deploy Insert Booking Payment Function
              run: aws lambda update-function-code --function-name insertBookingPayments --zip-file fileb://backend/confirm_booking_payment/insert-booking-payment-package.zip
